<?php

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementSeeder extends Seeder
{
    /**
     * Seed the achievements table.
     */
    public function run(): void
    {
        $achievements = [
            // ==========================================
            // COMBAT — kills, headshots, roadkills
            // ==========================================
            [
                'slug' => 'first-blood',
                'name' => 'First Blood',
                'description' => 'Get your first kill in combat.',
                'icon' => 'sword',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 1,
                'sort_order' => 1,
            ],
            [
                'slug' => 'centurion',
                'name' => 'Centurion',
                'description' => 'Reach 100 kills. A true century of combat.',
                'icon' => 'swords',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 100,
                'sort_order' => 2,
            ],
            [
                'slug' => 'warmonger',
                'name' => 'Warmonger',
                'description' => 'Achieve 500 kills on the battlefield.',
                'icon' => 'flame',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 500,
                'sort_order' => 3,
            ],
            [
                'slug' => 'veteran',
                'name' => 'Veteran',
                'description' => 'Achieve 1,000 kills in combat.',
                'icon' => 'shield',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 1000,
                'sort_order' => 4,
            ],
            [
                'slug' => 'terminator',
                'name' => 'Terminator',
                'description' => 'Achieve an incredible 5,000 kills in combat.',
                'icon' => 'skull',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 5000,
                'sort_order' => 5,
            ],
            [
                'slug' => 'god-of-war',
                'name' => 'God of War',
                'description' => 'Reach 10,000 kills. You are a legend.',
                'icon' => 'crown',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 10000,
                'sort_order' => 6,
            ],

            // Headshots
            [
                'slug' => 'sharpshooter',
                'name' => 'Sharpshooter',
                'description' => 'Land 50 headshots on enemy combatants.',
                'icon' => 'crosshair',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 50,
                'sort_order' => 7,
            ],
            [
                'slug' => 'marksman',
                'name' => 'Marksman',
                'description' => 'Land 250 headshots. Precision is your weapon.',
                'icon' => 'target',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 250,
                'sort_order' => 8,
            ],
            [
                'slug' => 'dead-eye',
                'name' => 'Dead Eye',
                'description' => 'Land 500 headshots. Every shot counts.',
                'icon' => 'eye',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 500,
                'sort_order' => 9,
            ],
            [
                'slug' => 'one-shot-legend',
                'name' => 'One Shot Legend',
                'description' => 'Land 1,000 headshots. They never see it coming.',
                'icon' => 'focus',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 1000,
                'sort_order' => 10,
            ],

            // Roadkills
            [
                'slug' => 'road-rage',
                'name' => 'Road Rage',
                'description' => 'Get 5 roadkills. Pedal to the metal.',
                'icon' => 'car',
                'color' => '#8b5cf6',
                'category' => 'combat',
                'stat_field' => 'total_roadkills',
                'threshold' => 5,
                'sort_order' => 11,
            ],
            [
                'slug' => 'road-warrior',
                'name' => 'Road Warrior',
                'description' => 'Get 25 roadkills. The highway is your weapon.',
                'icon' => 'truck',
                'color' => '#8b5cf6',
                'category' => 'combat',
                'stat_field' => 'total_roadkills',
                'threshold' => 25,
                'sort_order' => 12,
            ],
            [
                'slug' => 'speed-demon',
                'name' => 'Speed Demon',
                'description' => 'Get 100 roadkills. Nothing stops your vehicle.',
                'icon' => 'gauge',
                'color' => '#8b5cf6',
                'category' => 'combat',
                'stat_field' => 'total_roadkills',
                'threshold' => 100,
                'sort_order' => 13,
            ],

            // Team kills (negative achievement)
            [
                'slug' => 'friendly-fire',
                'name' => 'Friendly Fire',
                'description' => 'Accidentally teamkill 10 times. Watch your fire!',
                'icon' => 'shield-alert',
                'color' => '#6b7280',
                'category' => 'combat',
                'stat_field' => 'team_kills',
                'threshold' => 10,
                'sort_order' => 14,
            ],

            // ==========================================
            // SUPPORT — heals, supplies, bases
            // ==========================================
            [
                'slug' => 'first-aid',
                'name' => 'First Aid',
                'description' => 'Heal a teammate for the first time.',
                'icon' => 'heart-pulse',
                'color' => '#3b82f6',
                'category' => 'support',
                'stat_field' => 'heals_given',
                'threshold' => 1,
                'sort_order' => 20,
            ],
            [
                'slug' => 'field-medic',
                'name' => 'Field Medic',
                'description' => 'Heal teammates 100 times on the battlefield.',
                'icon' => 'stethoscope',
                'color' => '#3b82f6',
                'category' => 'support',
                'stat_field' => 'heals_given',
                'threshold' => 100,
                'sort_order' => 21,
            ],
            [
                'slug' => 'angel-of-mercy',
                'name' => 'Angel of Mercy',
                'description' => 'Heal teammates 500 times. A true lifesaver.',
                'icon' => 'heart',
                'color' => '#3b82f6',
                'category' => 'support',
                'stat_field' => 'heals_given',
                'threshold' => 500,
                'sort_order' => 22,
            ],
            [
                'slug' => 'miracle-worker',
                'name' => 'Miracle Worker',
                'description' => 'Heal teammates 1,000 times. The hospital on legs.',
                'icon' => 'cross',
                'color' => '#3b82f6',
                'category' => 'support',
                'stat_field' => 'heals_given',
                'threshold' => 1000,
                'sort_order' => 23,
            ],

            // Supplies
            [
                'slug' => 'supply-runner',
                'name' => 'Supply Runner',
                'description' => 'Deliver supplies 50 times.',
                'icon' => 'package',
                'color' => '#10b981',
                'category' => 'support',
                'stat_field' => 'supplies_delivered',
                'threshold' => 50,
                'sort_order' => 24,
            ],
            [
                'slug' => 'logistics-expert',
                'name' => 'Logistics Expert',
                'description' => 'Deliver 200 supply runs. The backbone of any army.',
                'icon' => 'boxes',
                'color' => '#10b981',
                'category' => 'support',
                'stat_field' => 'supplies_delivered',
                'threshold' => 200,
                'sort_order' => 25,
            ],
            [
                'slug' => 'quartermaster',
                'name' => 'Quartermaster',
                'description' => 'Deliver 500 supply runs. Nothing runs without you.',
                'icon' => 'warehouse',
                'color' => '#10b981',
                'category' => 'support',
                'stat_field' => 'supplies_delivered',
                'threshold' => 500,
                'sort_order' => 26,
            ],

            // Bases
            [
                'slug' => 'flag-raiser',
                'name' => 'Flag Raiser',
                'description' => 'Capture your first base.',
                'icon' => 'flag',
                'color' => '#f59e0b',
                'category' => 'support',
                'stat_field' => 'bases_captured',
                'threshold' => 1,
                'sort_order' => 27,
            ],
            [
                'slug' => 'base-conqueror',
                'name' => 'Base Conqueror',
                'description' => 'Capture 25 bases for your faction.',
                'icon' => 'flag-triangle-right',
                'color' => '#f59e0b',
                'category' => 'support',
                'stat_field' => 'bases_captured',
                'threshold' => 25,
                'sort_order' => 28,
            ],
            [
                'slug' => 'fortress-breaker',
                'name' => 'Fortress Breaker',
                'description' => 'Capture 100 bases. No position is safe.',
                'icon' => 'castle',
                'color' => '#f59e0b',
                'category' => 'support',
                'stat_field' => 'bases_captured',
                'threshold' => 100,
                'sort_order' => 29,
            ],

            // ==========================================
            // ACTIVITY — playtime, distance, shots, grenades
            // ==========================================

            // Playtime
            [
                'slug' => 'getting-started',
                'name' => 'Getting Started',
                'description' => 'Spend 10 hours in-game. Welcome to the fight.',
                'icon' => 'timer',
                'color' => '#a855f7',
                'category' => 'activity',
                'stat_field' => 'playtime_seconds',
                'threshold' => 36000,
                'sort_order' => 40,
            ],
            [
                'slug' => 'dedicated',
                'name' => 'Dedicated',
                'description' => 'Spend 100 hours in-game. True dedication.',
                'icon' => 'clock',
                'color' => '#a855f7',
                'category' => 'activity',
                'stat_field' => 'playtime_seconds',
                'threshold' => 360000,
                'sort_order' => 41,
            ],
            [
                'slug' => 'no-life',
                'name' => 'No Life',
                'description' => 'Spend 500 hours in-game. This IS your life.',
                'icon' => 'alarm-clock',
                'color' => '#a855f7',
                'category' => 'activity',
                'stat_field' => 'playtime_seconds',
                'threshold' => 1800000,
                'sort_order' => 42,
            ],
            [
                'slug' => 'eternal-soldier',
                'name' => 'Eternal Soldier',
                'description' => 'Spend 1,000 hours in-game. A permanent resident.',
                'icon' => 'infinity',
                'color' => '#a855f7',
                'category' => 'activity',
                'stat_field' => 'playtime_seconds',
                'threshold' => 3600000,
                'sort_order' => 43,
            ],

            // Distance
            [
                'slug' => 'marathon-runner',
                'name' => 'Marathon Runner',
                'description' => 'Travel a total distance of 100 kilometers.',
                'icon' => 'footprints',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 100000,
                'sort_order' => 44,
            ],
            [
                'slug' => 'long-hauler',
                'name' => 'Long Hauler',
                'description' => 'Travel 500km across the battlefield.',
                'icon' => 'map-pin',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 500000,
                'sort_order' => 45,
            ],
            [
                'slug' => 'globe-trotter',
                'name' => 'Globe Trotter',
                'description' => 'Travel 1,000km. You have seen every corner of Everon.',
                'icon' => 'globe',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 1000000,
                'sort_order' => 46,
            ],

            // Shots fired
            [
                'slug' => 'trigger-happy',
                'name' => 'Trigger Happy',
                'description' => 'Fire 10,000 shots. Ammunition is just a number.',
                'icon' => 'zap',
                'color' => '#eab308',
                'category' => 'activity',
                'stat_field' => 'shots_fired',
                'threshold' => 10000,
                'sort_order' => 47,
            ],
            [
                'slug' => 'bullet-hose',
                'name' => 'Bullet Hose',
                'description' => 'Fire 50,000 shots. Suppressive fire specialist.',
                'icon' => 'zap-off',
                'color' => '#eab308',
                'category' => 'activity',
                'stat_field' => 'shots_fired',
                'threshold' => 50000,
                'sort_order' => 48,
            ],

            // Grenades
            [
                'slug' => 'grenadier',
                'name' => 'Grenadier',
                'description' => 'Throw 100 grenades into the fray.',
                'icon' => 'bomb',
                'color' => '#f97316',
                'category' => 'activity',
                'stat_field' => 'grenades_thrown',
                'threshold' => 100,
                'sort_order' => 49,
            ],
            [
                'slug' => 'demolition-expert',
                'name' => 'Demolition Expert',
                'description' => 'Throw 500 grenades. Explosions are your specialty.',
                'icon' => 'bomb',
                'color' => '#f97316',
                'category' => 'activity',
                'stat_field' => 'grenades_thrown',
                'threshold' => 500,
                'sort_order' => 50,
            ],

            // ==========================================
            // SPECIAL — XP, damage, mixed
            // ==========================================
            [
                'slug' => 'xp-grinder',
                'name' => 'XP Grinder',
                'description' => 'Earn 50,000 total XP.',
                'icon' => 'star',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 50000,
                'sort_order' => 60,
            ],
            [
                'slug' => 'xp-master',
                'name' => 'XP Master',
                'description' => 'Earn 200,000 total XP. Experience breeds excellence.',
                'icon' => 'sparkles',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 200000,
                'sort_order' => 61,
            ],
            [
                'slug' => 'iron-skin',
                'name' => 'Iron Skin',
                'description' => 'Die 500 times. You always come back for more.',
                'icon' => 'shield-off',
                'color' => '#6b7280',
                'category' => 'special',
                'stat_field' => 'deaths',
                'threshold' => 500,
                'sort_order' => 62,
            ],
            [
                'slug' => 'punching-bag',
                'name' => 'Punching Bag',
                'description' => 'Die 2,000 times. Pain is temporary, glory is forever.',
                'icon' => 'ban',
                'color' => '#6b7280',
                'category' => 'special',
                'stat_field' => 'deaths',
                'threshold' => 2000,
                'sort_order' => 63,
            ],
            [
                'slug' => 'damage-dealer',
                'name' => 'Damage Dealer',
                'description' => 'Deal 100,000 total damage to enemies.',
                'icon' => 'activity',
                'color' => '#dc2626',
                'category' => 'special',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 100000,
                'sort_order' => 64,
            ],
            [
                'slug' => 'well-rounded',
                'name' => 'Well Rounded',
                'description' => 'Land 1,000 total hits across all body zones.',
                'icon' => 'circle-dot',
                'color' => '#14b8a6',
                'category' => 'special',
                'stat_field' => 'total_hits',
                'threshold' => 1000,
                'sort_order' => 65,
            ],

            // ==========================================
            // PRECISION — K/D ratio based (calculated)
            // ==========================================
            [
                'slug' => 'positive-kd',
                'name' => 'Positive K/D',
                'description' => 'Achieve a K/D ratio above 1.0 with at least 100 kills.',
                'icon' => 'trending-up',
                'color' => '#10b981',
                'category' => 'precision',
                'stat_field' => 'player_kills_count',
                'threshold' => 100,
                'sort_order' => 70,
            ],
            [
                'slug' => 'killer-instinct',
                'name' => 'Killer Instinct',
                'description' => 'Achieve a K/D ratio above 2.0 with at least 250 kills.',
                'icon' => 'flame',
                'color' => '#f59e0b',
                'category' => 'precision',
                'stat_field' => 'player_kills_count',
                'threshold' => 250,
                'sort_order' => 71,
            ],
            [
                'slug' => 'unstoppable',
                'name' => 'Unstoppable',
                'description' => 'Achieve a K/D ratio above 3.0 with at least 500 kills.',
                'icon' => 'zap',
                'color' => '#ef4444',
                'category' => 'precision',
                'stat_field' => 'player_kills_count',
                'threshold' => 500,
                'sort_order' => 72,
            ],

            // ==========================================
            // HEADSHOT PRECISION
            // ==========================================
            [
                'slug' => 'headshot-artist',
                'name' => 'Headshot Artist',
                'description' => 'Achieve 25% headshot accuracy with at least 200 kills.',
                'icon' => 'aperture',
                'color' => '#f97316',
                'category' => 'precision',
                'stat_field' => 'headshots',
                'threshold' => 50,
                'sort_order' => 73,
            ],
            [
                'slug' => 'headhunter',
                'name' => 'Headhunter',
                'description' => 'Achieve 40% headshot accuracy with at least 500 kills.',
                'icon' => 'crosshair',
                'color' => '#f97316',
                'category' => 'precision',
                'stat_field' => 'headshots',
                'threshold' => 200,
                'sort_order' => 74,
            ],

            // ==========================================
            // MILESTONES — big round numbers
            // ==========================================
            [
                'slug' => 'first-steps',
                'name' => 'First Steps',
                'description' => 'Play your first hour.',
                'icon' => 'footprints',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 3600,
                'sort_order' => 80,
            ],
            [
                'slug' => 'regular',
                'name' => 'Regular',
                'description' => 'Spend 50 hours in-game.',
                'icon' => 'user-check',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 180000,
                'sort_order' => 81,
            ],
            [
                'slug' => 'veteran-of-everon',
                'name' => 'Veteran of Everon',
                'description' => 'Spend 250 hours in-game. This is home now.',
                'icon' => 'medal',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 900000,
                'sort_order' => 82,
            ],
            [
                'slug' => 'triple-digit-kills',
                'name' => 'Triple Digit Kills',
                'description' => 'Reach 100 player kills.',
                'icon' => 'hash',
                'color' => '#ef4444',
                'category' => 'milestones',
                'stat_field' => 'player_kills_count',
                'threshold' => 100,
                'sort_order' => 83,
            ],
            [
                'slug' => 'half-k',
                'name' => 'Half K',
                'description' => 'Reach 500 player kills. Halfway to legendary.',
                'icon' => 'layers',
                'color' => '#ef4444',
                'category' => 'milestones',
                'stat_field' => 'player_kills_count',
                'threshold' => 500,
                'sort_order' => 84,
            ],
            [
                'slug' => 'double-century',
                'name' => 'Double Century',
                'description' => 'Reach 200 headshots.',
                'icon' => 'target',
                'color' => '#f97316',
                'category' => 'milestones',
                'stat_field' => 'headshots',
                'threshold' => 200,
                'sort_order' => 85,
            ],

            // ==========================================
            // TEAM PLAYER
            // ==========================================
            [
                'slug' => 'combat-medic',
                'name' => 'Combat Medic',
                'description' => 'Heal 250 teammates in the heat of battle.',
                'icon' => 'heart-handshake',
                'color' => '#3b82f6',
                'category' => 'teamwork',
                'stat_field' => 'heals_given',
                'threshold' => 250,
                'sort_order' => 90,
            ],
            [
                'slug' => 'lifeline',
                'name' => 'Lifeline',
                'description' => 'Heal 750 teammates. They depend on you.',
                'icon' => 'life-buoy',
                'color' => '#3b82f6',
                'category' => 'teamwork',
                'stat_field' => 'heals_given',
                'threshold' => 750,
                'sort_order' => 91,
            ],
            [
                'slug' => 'logistics-officer',
                'name' => 'Logistics Officer',
                'description' => 'Complete 100 supply deliveries.',
                'icon' => 'truck',
                'color' => '#10b981',
                'category' => 'teamwork',
                'stat_field' => 'supplies_delivered',
                'threshold' => 100,
                'sort_order' => 92,
            ],
            [
                'slug' => 'supply-master',
                'name' => 'Supply Master',
                'description' => 'Complete 350 supply deliveries.',
                'icon' => 'container',
                'color' => '#10b981',
                'category' => 'teamwork',
                'stat_field' => 'supplies_delivered',
                'threshold' => 350,
                'sort_order' => 93,
            ],
            [
                'slug' => 'objective-focused',
                'name' => 'Objective Focused',
                'description' => 'Capture 50 bases. PTFO is your motto.',
                'icon' => 'target',
                'color' => '#f59e0b',
                'category' => 'teamwork',
                'stat_field' => 'bases_captured',
                'threshold' => 50,
                'sort_order' => 94,
            ],
            [
                'slug' => 'base-hunter',
                'name' => 'Base Hunter',
                'description' => 'Capture 150 bases. You own the map.',
                'icon' => 'map',
                'color' => '#f59e0b',
                'category' => 'teamwork',
                'stat_field' => 'bases_captured',
                'threshold' => 150,
                'sort_order' => 95,
            ],

            // ==========================================
            // ENDURANCE — crazy high numbers
            // ==========================================
            [
                'slug' => 'world-traveler',
                'name' => 'World Traveler',
                'description' => 'Travel 2,000km across Everon.',
                'icon' => 'plane',
                'color' => '#06b6d4',
                'category' => 'endurance',
                'stat_field' => 'total_distance',
                'threshold' => 2000000,
                'sort_order' => 100,
            ],
            [
                'slug' => 'ammunition-waster',
                'name' => 'Ammunition Waster',
                'description' => 'Fire 100,000 shots. Spray and pray.',
                'icon' => 'radiation',
                'color' => '#eab308',
                'category' => 'endurance',
                'stat_field' => 'shots_fired',
                'threshold' => 100000,
                'sort_order' => 101,
            ],
            [
                'slug' => 'explosive-personality',
                'name' => 'Explosive Personality',
                'description' => 'Throw 1,000 grenades.',
                'icon' => 'sparkles',
                'color' => '#f97316',
                'category' => 'endurance',
                'stat_field' => 'grenades_thrown',
                'threshold' => 1000,
                'sort_order' => 102,
            ],
            [
                'slug' => 'xp-legend',
                'name' => 'XP Legend',
                'description' => 'Earn 500,000 total XP. Maximum experience.',
                'icon' => 'gem',
                'color' => '#22c55e',
                'category' => 'endurance',
                'stat_field' => 'xp_total',
                'threshold' => 500000,
                'sort_order' => 103,
            ],
            [
                'slug' => 'xp-god',
                'name' => 'XP God',
                'description' => 'Earn 1,000,000 total XP. Absolute perfection.',
                'icon' => 'trophy',
                'color' => '#22c55e',
                'category' => 'endurance',
                'stat_field' => 'xp_total',
                'threshold' => 1000000,
                'sort_order' => 104,
            ],
            [
                'slug' => 'damage-king',
                'name' => 'Damage King',
                'description' => 'Deal 500,000 total damage.',
                'icon' => 'swords',
                'color' => '#dc2626',
                'category' => 'endurance',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 500000,
                'sort_order' => 105,
            ],
            [
                'slug' => 'unstoppable-force',
                'name' => 'Unstoppable Force',
                'description' => 'Deal 1,000,000 total damage. Pure destruction.',
                'icon' => 'skull',
                'color' => '#dc2626',
                'category' => 'endurance',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 1000000,
                'sort_order' => 106,
            ],

            // ==========================================
            // FUN / JOKE ACHIEVEMENTS
            // ==========================================
            [
                'slug' => 'tourist',
                'name' => 'Tourist',
                'description' => 'Travel 10km. Just sightseeing?',
                'icon' => 'camera',
                'color' => '#06b6d4',
                'category' => 'fun',
                'stat_field' => 'total_distance',
                'threshold' => 10000,
                'sort_order' => 110,
            ],
            [
                'slug' => 'stormtrooper',
                'name' => 'Stormtrooper',
                'description' => 'Fire 25,000 shots with less than 500 kills.',
                'icon' => 'crosshair',
                'color' => '#6b7280',
                'category' => 'fun',
                'stat_field' => 'shots_fired',
                'threshold' => 25000,
                'sort_order' => 111,
            ],
            [
                'slug' => 'cant-touch-this',
                'name' => "Can't Touch This",
                'description' => 'Die less than 10 times with over 100 kills.',
                'icon' => 'shield-check',
                'color' => '#10b981',
                'category' => 'fun',
                'stat_field' => 'player_kills_count',
                'threshold' => 100,
                'sort_order' => 112,
            ],
            [
                'slug' => 'pacifist',
                'name' => 'Pacifist',
                'description' => 'Play 10 hours with less than 10 kills.',
                'icon' => 'heart',
                'color' => '#ec4899',
                'category' => 'fun',
                'stat_field' => 'playtime_seconds',
                'threshold' => 36000,
                'sort_order' => 113,
            ],
            [
                'slug' => 'grenade-spammer',
                'name' => 'Grenade Spammer',
                'description' => 'Throw 2,000 grenades. Boom boom boom!',
                'icon' => 'bomb',
                'color' => '#f97316',
                'category' => 'fun',
                'stat_field' => 'grenades_thrown',
                'threshold' => 2000,
                'sort_order' => 114,
            ],
            [
                'slug' => 'crash-test-dummy',
                'name' => 'Crash Test Dummy',
                'description' => 'Get 200 roadkills. The vehicle is the weapon.',
                'icon' => 'car',
                'color' => '#8b5cf6',
                'category' => 'fun',
                'stat_field' => 'total_roadkills',
                'threshold' => 200,
                'sort_order' => 115,
            ],

            // ==========================================
            // MORE KILL PROGRESSION
            // ==========================================
            [
                'slug' => 'serial-killer',
                'name' => 'Serial Killer',
                'description' => 'Reach 250 player kills.',
                'icon' => 'skull',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 250,
                'sort_order' => 120,
            ],
            [
                'slug' => 'mass-murderer',
                'name' => 'Mass Murderer',
                'description' => 'Reach 750 player kills.',
                'icon' => 'skull',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 750,
                'sort_order' => 121,
            ],
            [
                'slug' => 'legendary-assassin',
                'name' => 'Legendary Assassin',
                'description' => 'Reach 2,000 player kills.',
                'icon' => 'skull',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 2000,
                'sort_order' => 122,
            ],
            [
                'slug' => 'death-incarnate',
                'name' => 'Death Incarnate',
                'description' => 'Reach 3,500 player kills.',
                'icon' => 'skull',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 3500,
                'sort_order' => 123,
            ],
            [
                'slug' => 'apocalypse',
                'name' => 'Apocalypse',
                'description' => 'Reach 7,500 player kills. You are the end.',
                'icon' => 'skull',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 7500,
                'sort_order' => 124,
            ],
            [
                'slug' => 'armageddon',
                'name' => 'Armageddon',
                'description' => 'Reach 15,000 player kills. The final boss.',
                'icon' => 'skull',
                'color' => '#ef4444',
                'category' => 'combat',
                'stat_field' => 'player_kills_count',
                'threshold' => 15000,
                'sort_order' => 125,
            ],

            // ==========================================
            // MORE HEADSHOT PROGRESSION
            // ==========================================
            [
                'slug' => 'headshot-novice',
                'name' => 'Headshot Novice',
                'description' => 'Land 25 headshots.',
                'icon' => 'circle-dot',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 25,
                'sort_order' => 130,
            ],
            [
                'slug' => 'headshot-expert',
                'name' => 'Headshot Expert',
                'description' => 'Land 150 headshots.',
                'icon' => 'crosshair',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 150,
                'sort_order' => 131,
            ],
            [
                'slug' => 'headshot-master',
                'name' => 'Headshot Master',
                'description' => 'Land 750 headshots.',
                'icon' => 'target',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 750,
                'sort_order' => 132,
            ],
            [
                'slug' => 'headshot-grandmaster',
                'name' => 'Headshot Grandmaster',
                'description' => 'Land 2,000 headshots.',
                'icon' => 'focus',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 2000,
                'sort_order' => 133,
            ],
            [
                'slug' => 'headshot-deity',
                'name' => 'Headshot Deity',
                'description' => 'Land 5,000 headshots. The ultimate sniper.',
                'icon' => 'zap',
                'color' => '#f97316',
                'category' => 'combat',
                'stat_field' => 'headshots',
                'threshold' => 5000,
                'sort_order' => 134,
            ],

            // ==========================================
            // MORE SUPPORT PROGRESSION
            // ==========================================
            [
                'slug' => 'medic-initiate',
                'name' => 'Medic Initiate',
                'description' => 'Heal teammates 50 times.',
                'icon' => 'plus-circle',
                'color' => '#3b82f6',
                'category' => 'support',
                'stat_field' => 'heals_given',
                'threshold' => 50,
                'sort_order' => 140,
            ],
            [
                'slug' => 'surgeon',
                'name' => 'Surgeon',
                'description' => 'Heal teammates 250 times.',
                'icon' => 'activity',
                'color' => '#3b82f6',
                'category' => 'support',
                'stat_field' => 'heals_given',
                'threshold' => 250,
                'sort_order' => 141,
            ],
            [
                'slug' => 'doctor',
                'name' => 'Doctor',
                'description' => 'Heal teammates 750 times.',
                'icon' => 'heart-pulse',
                'color' => '#3b82f6',
                'category' => 'support',
                'stat_field' => 'heals_given',
                'threshold' => 750,
                'sort_order' => 142,
            ],
            [
                'slug' => 'medical-legend',
                'name' => 'Medical Legend',
                'description' => 'Heal teammates 2,000 times.',
                'icon' => 'cross',
                'color' => '#3b82f6',
                'category' => 'support',
                'stat_field' => 'heals_given',
                'threshold' => 2000,
                'sort_order' => 143,
            ],
            [
                'slug' => 'supply-sergeant',
                'name' => 'Supply Sergeant',
                'description' => 'Complete 25 supply deliveries.',
                'icon' => 'package-2',
                'color' => '#10b981',
                'category' => 'support',
                'stat_field' => 'supplies_delivered',
                'threshold' => 25,
                'sort_order' => 144,
            ],
            [
                'slug' => 'supply-lieutenant',
                'name' => 'Supply Lieutenant',
                'description' => 'Complete 150 supply deliveries.',
                'icon' => 'truck',
                'color' => '#10b981',
                'category' => 'support',
                'stat_field' => 'supplies_delivered',
                'threshold' => 150,
                'sort_order' => 145,
            ],
            [
                'slug' => 'supply-commander',
                'name' => 'Supply Commander',
                'description' => 'Complete 750 supply deliveries.',
                'icon' => 'container',
                'color' => '#10b981',
                'category' => 'support',
                'stat_field' => 'supplies_delivered',
                'threshold' => 750,
                'sort_order' => 146,
            ],
            [
                'slug' => 'base-raider',
                'name' => 'Base Raider',
                'description' => 'Capture 10 bases.',
                'icon' => 'flag',
                'color' => '#f59e0b',
                'category' => 'support',
                'stat_field' => 'bases_captured',
                'threshold' => 10,
                'sort_order' => 147,
            ],
            [
                'slug' => 'base-dominator',
                'name' => 'Base Dominator',
                'description' => 'Capture 200 bases.',
                'icon' => 'castle',
                'color' => '#f59e0b',
                'category' => 'support',
                'stat_field' => 'bases_captured',
                'threshold' => 200,
                'sort_order' => 148,
            ],
            [
                'slug' => 'base-emperor',
                'name' => 'Base Emperor',
                'description' => 'Capture 500 bases. You rule Everon.',
                'icon' => 'crown',
                'color' => '#f59e0b',
                'category' => 'support',
                'stat_field' => 'bases_captured',
                'threshold' => 500,
                'sort_order' => 149,
            ],

            // ==========================================
            // MORE DAMAGE PROGRESSION
            // ==========================================
            [
                'slug' => 'pain-dealer',
                'name' => 'Pain Dealer',
                'description' => 'Deal 25,000 total damage.',
                'icon' => 'flame',
                'color' => '#dc2626',
                'category' => 'special',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 25000,
                'sort_order' => 150,
            ],
            [
                'slug' => 'hurt-locker',
                'name' => 'Hurt Locker',
                'description' => 'Deal 50,000 total damage.',
                'icon' => 'zap',
                'color' => '#dc2626',
                'category' => 'special',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 50000,
                'sort_order' => 151,
            ],
            [
                'slug' => 'destruction',
                'name' => 'Destruction',
                'description' => 'Deal 250,000 total damage.',
                'icon' => 'bomb',
                'color' => '#dc2626',
                'category' => 'special',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 250000,
                'sort_order' => 152,
            ],
            [
                'slug' => 'devastation',
                'name' => 'Devastation',
                'description' => 'Deal 750,000 total damage.',
                'icon' => 'flame',
                'color' => '#dc2626',
                'category' => 'special',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 750000,
                'sort_order' => 153,
            ],
            [
                'slug' => 'cataclysm',
                'name' => 'Cataclysm',
                'description' => 'Deal 1,500,000 total damage.',
                'icon' => 'skull',
                'color' => '#dc2626',
                'category' => 'special',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 1500000,
                'sort_order' => 154,
            ],
            [
                'slug' => 'oblivion',
                'name' => 'Oblivion',
                'description' => 'Deal 3,000,000 total damage. Total annihilation.',
                'icon' => 'radiation',
                'color' => '#dc2626',
                'category' => 'special',
                'stat_field' => 'total_damage_dealt',
                'threshold' => 3000000,
                'sort_order' => 155,
            ],

            // ==========================================
            // MORE SHOTS FIRED
            // ==========================================
            [
                'slug' => 'spray-master',
                'name' => 'Spray Master',
                'description' => 'Fire 5,000 shots.',
                'icon' => 'zap',
                'color' => '#eab308',
                'category' => 'activity',
                'stat_field' => 'shots_fired',
                'threshold' => 5000,
                'sort_order' => 160,
            ],
            [
                'slug' => 'gunner',
                'name' => 'Gunner',
                'description' => 'Fire 25,000 shots.',
                'icon' => 'crosshair',
                'color' => '#eab308',
                'category' => 'activity',
                'stat_field' => 'shots_fired',
                'threshold' => 25000,
                'sort_order' => 161,
            ],
            [
                'slug' => 'heavy-gunner',
                'name' => 'Heavy Gunner',
                'description' => 'Fire 75,000 shots.',
                'icon' => 'target',
                'color' => '#eab308',
                'category' => 'activity',
                'stat_field' => 'shots_fired',
                'threshold' => 75000,
                'sort_order' => 162,
            ],
            [
                'slug' => 'suppressive-fire',
                'name' => 'Suppressive Fire',
                'description' => 'Fire 150,000 shots.',
                'icon' => 'zap-off',
                'color' => '#eab308',
                'category' => 'activity',
                'stat_field' => 'shots_fired',
                'threshold' => 150000,
                'sort_order' => 163,
            ],
            [
                'slug' => 'full-auto-fanatic',
                'name' => 'Full Auto Fanatic',
                'description' => 'Fire 250,000 shots. Never release the trigger.',
                'icon' => 'flame',
                'color' => '#eab308',
                'category' => 'activity',
                'stat_field' => 'shots_fired',
                'threshold' => 250000,
                'sort_order' => 164,
            ],

            // ==========================================
            // MORE GRENADES
            // ==========================================
            [
                'slug' => 'grenade-novice',
                'name' => 'Grenade Novice',
                'description' => 'Throw 50 grenades.',
                'icon' => 'bomb',
                'color' => '#f97316',
                'category' => 'activity',
                'stat_field' => 'grenades_thrown',
                'threshold' => 50,
                'sort_order' => 170,
            ],
            [
                'slug' => 'grenade-expert',
                'name' => 'Grenade Expert',
                'description' => 'Throw 250 grenades.',
                'icon' => 'bomb',
                'color' => '#f97316',
                'category' => 'activity',
                'stat_field' => 'grenades_thrown',
                'threshold' => 250,
                'sort_order' => 171,
            ],
            [
                'slug' => 'bombardier',
                'name' => 'Bombardier',
                'description' => 'Throw 750 grenades.',
                'icon' => 'flame',
                'color' => '#f97316',
                'category' => 'activity',
                'stat_field' => 'grenades_thrown',
                'threshold' => 750,
                'sort_order' => 172,
            ],
            [
                'slug' => 'artillery',
                'name' => 'Artillery',
                'description' => 'Throw 1,500 grenades.',
                'icon' => 'sparkles',
                'color' => '#f97316',
                'category' => 'activity',
                'stat_field' => 'grenades_thrown',
                'threshold' => 1500,
                'sort_order' => 173,
            ],
            [
                'slug' => 'grenade-maniac',
                'name' => 'Grenade Maniac',
                'description' => 'Throw 3,000 grenades. Explosions everywhere!',
                'icon' => 'radiation',
                'color' => '#f97316',
                'category' => 'activity',
                'stat_field' => 'grenades_thrown',
                'threshold' => 3000,
                'sort_order' => 174,
            ],

            // ==========================================
            // MORE XP PROGRESSION
            // ==========================================
            [
                'slug' => 'xp-beginner',
                'name' => 'XP Beginner',
                'description' => 'Earn 10,000 total XP.',
                'icon' => 'star',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 10000,
                'sort_order' => 180,
            ],
            [
                'slug' => 'xp-adept',
                'name' => 'XP Adept',
                'description' => 'Earn 75,000 total XP.',
                'icon' => 'sparkle',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 75000,
                'sort_order' => 181,
            ],
            [
                'slug' => 'xp-veteran',
                'name' => 'XP Veteran',
                'description' => 'Earn 150,000 total XP.',
                'icon' => 'award',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 150000,
                'sort_order' => 182,
            ],
            [
                'slug' => 'xp-elite',
                'name' => 'XP Elite',
                'description' => 'Earn 350,000 total XP.',
                'icon' => 'gem',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 350000,
                'sort_order' => 183,
            ],
            [
                'slug' => 'xp-champion',
                'name' => 'XP Champion',
                'description' => 'Earn 750,000 total XP.',
                'icon' => 'trophy',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 750000,
                'sort_order' => 184,
            ],
            [
                'slug' => 'xp-immortal',
                'name' => 'XP Immortal',
                'description' => 'Earn 2,000,000 total XP.',
                'icon' => 'crown',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 2000000,
                'sort_order' => 185,
            ],
            [
                'slug' => 'xp-transcendent',
                'name' => 'XP Transcendent',
                'description' => 'Earn 5,000,000 total XP. Beyond mortal limits.',
                'icon' => 'sparkles',
                'color' => '#22c55e',
                'category' => 'special',
                'stat_field' => 'xp_total',
                'threshold' => 5000000,
                'sort_order' => 186,
            ],

            // ==========================================
            // TEAM KILLS (negative achievements)
            // ==========================================
            [
                'slug' => 'team-killer',
                'name' => 'Team Killer',
                'description' => 'Teamkill 5 times. Check your targets!',
                'icon' => 'alert-triangle',
                'color' => '#6b7280',
                'category' => 'fun',
                'stat_field' => 'team_kills',
                'threshold' => 5,
                'sort_order' => 190,
            ],
            [
                'slug' => 'oops',
                'name' => 'Oops',
                'description' => 'Teamkill 25 times. Maybe get glasses?',
                'icon' => 'ban',
                'color' => '#6b7280',
                'category' => 'fun',
                'stat_field' => 'team_kills',
                'threshold' => 25,
                'sort_order' => 191,
            ],
            [
                'slug' => 'war-criminal',
                'name' => 'War Criminal',
                'description' => 'Teamkill 50 times. You monster.',
                'icon' => 'skull',
                'color' => '#6b7280',
                'category' => 'fun',
                'stat_field' => 'team_kills',
                'threshold' => 50,
                'sort_order' => 192,
            ],
            [
                'slug' => 'squad-wiper',
                'name' => 'Squad Wiper',
                'description' => 'Teamkill 100 times. Your team fears you.',
                'icon' => 'x-circle',
                'color' => '#6b7280',
                'category' => 'fun',
                'stat_field' => 'team_kills',
                'threshold' => 100,
                'sort_order' => 193,
            ],

            // ==========================================
            // MORE PLAYTIME RANKS
            // ==========================================
            [
                'slug' => 'newcomer',
                'name' => 'Newcomer',
                'description' => 'Spend 1 hour in-game.',
                'icon' => 'user-plus',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 3600,
                'sort_order' => 200,
            ],
            [
                'slug' => 'rookie',
                'name' => 'Rookie',
                'description' => 'Spend 5 hours in-game.',
                'icon' => 'user',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 18000,
                'sort_order' => 201,
            ],
            [
                'slug' => 'private',
                'name' => 'Private',
                'description' => 'Spend 25 hours in-game.',
                'icon' => 'user-check',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 90000,
                'sort_order' => 202,
            ],
            [
                'slug' => 'corporal',
                'name' => 'Corporal',
                'description' => 'Spend 75 hours in-game.',
                'icon' => 'shield',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 270000,
                'sort_order' => 203,
            ],
            [
                'slug' => 'sergeant',
                'name' => 'Sergeant',
                'description' => 'Spend 150 hours in-game.',
                'icon' => 'shield-check',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 540000,
                'sort_order' => 204,
            ],
            [
                'slug' => 'lieutenant',
                'name' => 'Lieutenant',
                'description' => 'Spend 300 hours in-game.',
                'icon' => 'medal',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 1080000,
                'sort_order' => 205,
            ],
            [
                'slug' => 'captain',
                'name' => 'Captain',
                'description' => 'Spend 500 hours in-game.',
                'icon' => 'award',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 1800000,
                'sort_order' => 206,
            ],
            [
                'slug' => 'major',
                'name' => 'Major',
                'description' => 'Spend 750 hours in-game.',
                'icon' => 'star',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 2700000,
                'sort_order' => 207,
            ],
            [
                'slug' => 'colonel',
                'name' => 'Colonel',
                'description' => 'Spend 1,250 hours in-game.',
                'icon' => 'crown',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 4500000,
                'sort_order' => 208,
            ],
            [
                'slug' => 'general',
                'name' => 'General',
                'description' => 'Spend 2,000 hours in-game. The supreme commander.',
                'icon' => 'trophy',
                'color' => '#a855f7',
                'category' => 'milestones',
                'stat_field' => 'playtime_seconds',
                'threshold' => 7200000,
                'sort_order' => 209,
            ],

            // ==========================================
            // MORE DISTANCE TIERS
            // ==========================================
            [
                'slug' => 'walker',
                'name' => 'Walker',
                'description' => 'Travel 10km across the battlefield.',
                'icon' => 'footprints',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 10000,
                'sort_order' => 220,
            ],
            [
                'slug' => 'hiker',
                'name' => 'Hiker',
                'description' => 'Travel 50km across Everon.',
                'icon' => 'map',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 50000,
                'sort_order' => 221,
            ],
            [
                'slug' => 'trekker',
                'name' => 'Trekker',
                'description' => 'Travel 250km across the map.',
                'icon' => 'map-pin',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 250000,
                'sort_order' => 222,
            ],
            [
                'slug' => 'explorer',
                'name' => 'Explorer',
                'description' => 'Travel 750km. You know every trail.',
                'icon' => 'compass',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 750000,
                'sort_order' => 223,
            ],
            [
                'slug' => 'nomad',
                'name' => 'Nomad',
                'description' => 'Travel 1,500km. Never in one place.',
                'icon' => 'map-pinned',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 1500000,
                'sort_order' => 224,
            ],
            [
                'slug' => 'wanderer',
                'name' => 'Wanderer',
                'description' => 'Travel 3,000km. The eternal wanderer.',
                'icon' => 'navigation',
                'color' => '#06b6d4',
                'category' => 'activity',
                'stat_field' => 'total_distance',
                'threshold' => 3000000,
                'sort_order' => 225,
            ],

            // ==========================================
            // HIT ZONE SPECIALISTS
            // ==========================================
            [
                'slug' => 'head-hunter',
                'name' => 'Head Hunter',
                'description' => 'Land 250 head hits.',
                'icon' => 'crosshair',
                'color' => '#f97316',
                'category' => 'precision',
                'stat_field' => 'hits_head',
                'threshold' => 250,
                'sort_order' => 230,
            ],
            [
                'slug' => 'headshot-machine',
                'name' => 'Headshot Machine',
                'description' => 'Land 1,000 head hits.',
                'icon' => 'target',
                'color' => '#f97316',
                'category' => 'precision',
                'stat_field' => 'hits_head',
                'threshold' => 1000,
                'sort_order' => 231,
            ],
            [
                'slug' => 'torso-terminator',
                'name' => 'Torso Terminator',
                'description' => 'Land 2,000 torso hits.',
                'icon' => 'crosshair',
                'color' => '#ef4444',
                'category' => 'precision',
                'stat_field' => 'hits_torso',
                'threshold' => 2000,
                'sort_order' => 232,
            ],
            [
                'slug' => 'leg-breaker',
                'name' => 'Leg Breaker',
                'description' => 'Land 1,000 leg hits.',
                'icon' => 'footprints',
                'color' => '#f59e0b',
                'category' => 'precision',
                'stat_field' => 'hits_legs',
                'threshold' => 1000,
                'sort_order' => 233,
            ],
            [
                'slug' => 'arm-wrestler',
                'name' => 'Arm Wrestler',
                'description' => 'Land 1,000 arm hits.',
                'icon' => 'hand',
                'color' => '#3b82f6',
                'category' => 'precision',
                'stat_field' => 'hits_arms',
                'threshold' => 1000,
                'sort_order' => 234,
            ],
            [
                'slug' => 'well-balanced-fighter',
                'name' => 'Well Balanced Fighter',
                'description' => 'Land 200 hits in each body zone.',
                'icon' => 'circle-dot',
                'color' => '#14b8a6',
                'category' => 'precision',
                'stat_field' => 'total_hits',
                'threshold' => 800,
                'sort_order' => 235,
            ],
            [
                'slug' => 'precision-striker',
                'name' => 'Precision Striker',
                'description' => 'Land 5,000 head hits. Perfect accuracy.',
                'icon' => 'zap',
                'color' => '#f97316',
                'category' => 'precision',
                'stat_field' => 'hits_head',
                'threshold' => 5000,
                'sort_order' => 236,
            ],

            // ==========================================
            // HIT TOTALS
            // ==========================================
            [
                'slug' => 'getting-better',
                'name' => 'Getting Better',
                'description' => 'Land 5,000 total hits.',
                'icon' => 'trending-up',
                'color' => '#14b8a6',
                'category' => 'special',
                'stat_field' => 'total_hits',
                'threshold' => 5000,
                'sort_order' => 240,
            ],
            [
                'slug' => 'precision-fighter',
                'name' => 'Precision Fighter',
                'description' => 'Land 15,000 total hits.',
                'icon' => 'crosshair',
                'color' => '#14b8a6',
                'category' => 'special',
                'stat_field' => 'total_hits',
                'threshold' => 15000,
                'sort_order' => 241,
            ],
            [
                'slug' => 'hit-master',
                'name' => 'Hit Master',
                'description' => 'Land 35,000 total hits.',
                'icon' => 'target',
                'color' => '#14b8a6',
                'category' => 'special',
                'stat_field' => 'total_hits',
                'threshold' => 35000,
                'sort_order' => 242,
            ],
            [
                'slug' => 'impact-legend',
                'name' => 'Impact Legend',
                'description' => 'Land 75,000 total hits.',
                'icon' => 'zap',
                'color' => '#14b8a6',
                'category' => 'special',
                'stat_field' => 'total_hits',
                'threshold' => 75000,
                'sort_order' => 243,
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::updateOrCreate(
                ['slug' => $achievement['slug']],
                $achievement
            );
        }
    }
}
